version: '3'
services:
  app:
    build: .
    container_name: financetracker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/financetracker
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
