# save row

POST http://localhost:5000/api/save
Content-Type: application/json

{
    "date": "2025-01-01T12:00:00.000Z",
    "expenses": "Groceries",
    "amount": 150.0,
    "budget_balance": 850.0
}

### TEST
GET http://localhost:5000/api/test

